# Generated by Django 2.0.7 on 2021-10-04 02:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_auto_20211004_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 2, 53, 44, 653429, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 2, 53, 44, 653049, tzinfo=utc)),
        ),
    ]
