# Generated by Django 3.2.7 on 2021-10-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0007_auto_20211004_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aprroved_comment',
            new_name='approved_comment',
        ),
    ]
