# Generated by Django 2.0.7 on 2021-10-04 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_auto_20211003_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 2, 48, 51, 586271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 2, 48, 51, 585908, tzinfo=utc)),
        ),
    ]
